CREATE DATABASE BTL
GO
USE BTL
GO

CREATE TABLE NHANVIEN(
	MANV CHAR(10) NOT NULL,
	TEN NVARCHAR(50) NOT NULL,
	EMAIL VARCHAR(255) UNIQUE,
	GIOITINH NVARCHAR(10) NOT NULL,
	SDT CHAR(10) UNIQUE NOT NULL,
	NGAYSINH DATE NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	CHUCVU NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE TRUYEN(
	MATRUYEN CHAR(10) NOT NULL,
	MATG CHAR(10) NOT NULL,
	MANV CHAR(10) NOT NULL,
	TENTRUYEN NVARCHAR(50) NOT NULL,
	SOLUONG INT NOT NULL,
	NXB NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE TACGIA(
	MATG CHAR(10) NOT NULL,
	TEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL
)
GO
CREATE TABLE DOCGIA(
	MADG CHAR(10) NOT NULL,
	TEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH NVARCHAR(10) NOT NULL,
	SDT CHAR(10) UNIQUE NOT NULL,
	EMAIL VARCHAR(255) UNIQUE,
	DIACHI NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE PHIEUMUON(
	MAPHIEUMUON CHAR(10) NOT NULL,
	MANV CHAR(10) NOT NULL,
	MADG CHAR(10) NOT NULL,
	NGAYMUON DATE NOT NULL,
	NGAYTRA DATE NOT NULL,
	TONGSL INT NOT NULL
)
GO
CREATE TABLE DANHSACHMUON(
	MAPHIEUMUON CHAR(10) NOT NULL,
	MATRUYEN CHAR(10) NOT NULL,
	SOLUONG INT NOT NULL
)
GO

-- RANG BUOC KHOA CHINH
ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)

ALTER TABLE TRUYEN
ADD CONSTRAINT PK_TRUYEN PRIMARY KEY(MATRUYEN)

ALTER TABLE TACGIA
ADD CONSTRAINT PK_TACGIA PRIMARY KEY(MATG)

ALTER TABLE DOCGIA
ADD CONSTRAINT PK_DOCGIA PRIMARY KEY(MADG)

ALTER TABLE PHIEUMUON
ADD CONSTRAINT PK_PHIEUMUON PRIMARY KEY(MAPHIEUMUON)

ALTER TABLE DANHSACHMUON
ADD CONSTRAINT PK_DANHSACHMUON PRIMARY KEY(MAPHIEUMUON, MATRUYEN)

-- RANG BUOC KHOA NGOAI
